import type { Brand, RecordItem, Service } from "./types";

export const BRANDS: Brand[] = [
  { id: "A", name: "Brand A", color: "#266363" },
  { id: "B", name: "Brand B", color: "#3d5a80" },
  { id: "C", name: "Brand C", color: "#8b6914" },
  { id: "D", name: "Brand D", color: "#6b4f4f" },
];

export const SERVICES: Service[] = [
  { id: "X", name: "Service X" },
  { id: "Y", name: "Service Y" },
  { id: "Z", name: "Service Z" },
  { id: "W", name: "Service W" },
];

export const OWNERS = ["S. Ahmed", "R. Cole", "M. Ortiz", "J. Park"];

function daysAgo(n: number) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

/** Sample portfolio matching the client brief — illustrative but realistic. */
export const SEED_RECORDS: RecordItem[] = [
  {
    id: "r1",
    company: "Acme Logistics",
    contact: "Nina Patel",
    owner: "S. Ahmed",
    brandId: "A",
    stage: "Active Client",
    clientId: "CL-8492",
    services: ["X", "Z", "W"],
    marketingEmailsOn: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(12),
    clientSince: daysAgo(60),
  },
  {
    id: "r2",
    company: "Northline Co.",
    contact: "Tom Briggs",
    owner: "R. Cole",
    brandId: "C",
    stage: "Active Client",
    clientId: "CL-8510",
    services: ["X"],
    marketingEmailsOn: false,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(8),
    clientSince: daysAgo(40),
  },
  {
    id: "r3",
    company: "Pierpoint Ltd",
    contact: "Elena Ruiz",
    owner: "S. Ahmed",
    brandId: "A",
    stage: "Active Client",
    clientId: "CL-8521",
    services: ["X", "Z"],
    marketingEmailsOn: false,
    createdAt: daysAgo(55),
    updatedAt: daysAgo(5),
    clientSince: daysAgo(30),
  },
  {
    id: "r4",
    company: "Riverbend Group",
    contact: "Chris Hale",
    owner: "M. Ortiz",
    brandId: "B",
    stage: "Active Client",
    clientId: "CL-8533",
    services: ["Y", "W"],
    marketingEmailsOn: false,
    createdAt: daysAgo(48),
    updatedAt: daysAgo(10),
    clientSince: daysAgo(25),
  },
  {
    id: "r5",
    company: "Helix Partners",
    contact: "Amy Cho",
    owner: "J. Park",
    brandId: "D",
    stage: "Active Client",
    clientId: "CL-8540",
    services: ["X", "Y"],
    marketingEmailsOn: false,
    createdAt: daysAgo(42),
    updatedAt: daysAgo(3),
    clientSince: daysAgo(20),
  },
  {
    id: "r6",
    company: "Cedar & Co",
    contact: "Mark Webb",
    owner: "S. Ahmed",
    brandId: "A",
    stage: "Active Pipeline",
    clientId: null,
    services: ["X"],
    marketingEmailsOn: false,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(2),
    clientSince: null,
  },
  {
    id: "r7",
    company: "Orbit Media",
    contact: "Sara Quinn",
    owner: "R. Cole",
    brandId: "B",
    stage: "Active Pipeline",
    clientId: null,
    services: [],
    marketingEmailsOn: false,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
    clientSince: null,
  },
  {
    id: "r8",
    company: "Summit Foods",
    contact: "Dan Frost",
    owner: "M. Ortiz",
    brandId: "C",
    stage: "Active Pipeline",
    clientId: null,
    services: ["Z"],
    marketingEmailsOn: false,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(1),
    clientSince: null,
  },
  {
    id: "r9",
    company: "Lantern Soft",
    contact: "Priya Nair",
    owner: "J. Park",
    brandId: "D",
    stage: "Lead",
    clientId: null,
    services: [],
    marketingEmailsOn: true,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(0),
    clientSince: null,
  },
  {
    id: "r10",
    company: "Blue Harbor",
    contact: "Leo Grant",
    owner: "S. Ahmed",
    brandId: "A",
    stage: "Lead",
    clientId: null,
    services: [],
    marketingEmailsOn: true,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(0),
    clientSince: null,
  },
  {
    id: "r11",
    company: "Kite Retail",
    contact: "Uma Seth",
    owner: "R. Cole",
    brandId: "B",
    stage: "Lead",
    clientId: null,
    services: [],
    marketingEmailsOn: true,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
    clientSince: null,
  },
  {
    id: "r12",
    company: "Foghorn Labs",
    contact: "Ben Adler",
    owner: "M. Ortiz",
    brandId: "C",
    stage: "Lead",
    clientId: null,
    services: [],
    marketingEmailsOn: true,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
    clientSince: null,
  },
  {
    id: "r13",
    company: "Iron Gate",
    contact: "Claire Moss",
    owner: "J. Park",
    brandId: "A",
    stage: "Active Client",
    clientId: "CL-8548",
    services: ["X", "Y", "Z"],
    marketingEmailsOn: false,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(15),
    clientSince: daysAgo(70),
  },
  {
    id: "r14",
    company: "Velvet Line",
    contact: "Omar Said",
    owner: "S. Ahmed",
    brandId: "B",
    stage: "Active Client",
    clientId: "CL-8555",
    services: ["Y"],
    marketingEmailsOn: false,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(7),
    clientSince: daysAgo(45),
  },
  {
    id: "r15",
    company: "Quiet Oak",
    contact: "Helen Fry",
    owner: "R. Cole",
    brandId: "D",
    stage: "Active Pipeline",
    clientId: null,
    services: ["X"],
    marketingEmailsOn: false,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(0),
    clientSince: null,
  },
];

export const INITIAL_NEXT_CLIENT_SEQ = 8556;
